### ISSUE TITLE
Sweep functionality documentation request

### ISSUE THREAD

**Issue by xalier1** [alessandromaggio/pythonping#64] opened 2021-03-06 18:02 UTC
**Describe the bug**
Ping sweep functionality is disabled unless ping is called  with size=None or size=0

**To Reproduce**
1.  Call ping without size=None  - ret = ping(ip,sweep_start=10 ,sweep_end=109,timeout=2,match=True)
2.  Use wireshark or equivalent and look at the icmp messages being sent
3. Observe that payload is all the same size, equivalent to ping being called with size=1
4. Call ping with size=None - ret = ping(ip,size=None,sweep_start=10 sweep_end=109,timeout=2,match=True)
5. Use wireshark or equivalent and look at the icmp messages being sent
6. Observe that payload size is now changing from one icmp request to the next

**Expected behavior**
It wasn't clear from the documentation that in order to use sweep functionality that  ping must be called with size explicitly set to None or 0.  Please  update the documentation to make this clear.

**Comment by alessandromaggio** [comment] 2021-03-07 07:37
Hello!

You are making a good point. I will try to verify it, but if that's the way it is, rather than updating the documentation, I think the correct behavior, I would make it ignore the size parameter if the sweep sizes (start and end) are set instead. The problem is happening because the default size is 1 most probably.

**Comment by xalier1** [comment] 2021-03-07 15:44
Hi

Thanks for your quick response.   I  appreciate being able to use the ping functionality  of  pythonping module. Thanks for authoring, maintaining it and making it available on github. Included below is a response to your response and an additional discussion item.

As you have said in your response, giving  the sweep sizes priority over size and count if sweep sizes are set makes sense as a  better solution.   I am new to Python but it seems that since   both size and count   can conflict with sweep sizes, an alternate better solution might be to  resolve the  conflict programmatically  in  the  ping function.   As a suggestion  would the following work?  Default both size and count to None as  is already done with sweep_start and sweep_end.   If   a   call to  ping is made with a conflict like  sweep sizes set and size set, raise a   ValueError('with explanation of the conflict') exception.  If ping is called and sweep sizes are not set,   and   count and size  are not set, then programmatically set size=1 and count=4 (eg the current defaults). Adding a ValueError exception on a parameter conflict rather than being silent about  the conflict  would seem like a good thing to do.

As a discussion item,  I  was wondering why the sequence number is not matched between request and response when ping is called with match=True.  It would be convenient for me if match=True could be redefined to do this.  I am currently using  the sweep functionality to force a match between request and response. The sweep functionality is very useful but for my current application,  if match=True  included  sequence number match,  then I would not be using sweep functionality.

**Comment by alessandromaggio** [comment] 2021-03-12 06:58
In the end I simply inverted an if-elif construct in the ping function. Now if you set sweep_start and sweep_end, size is ignored, which is the correct behavior as setting a static size _and_ sweep settings make no sense, so I am assuming this is the wanted behavior for most users.

Changes are already out in version 1.0.16, which is already available for download with `pip`. I am going to close this, thanks for the clear notification of the issue and good pinging! And if you have time, feel free to pick an open issue and contribute :)

**Closed by alessandromaggio** 2021-03-12 06:58 UTC
