### ISSUE TITLE
hang while target is unreachable

### ISSUE THREAD

**Issue by wellsgz** [alessandromaggio/pythonping#12] opened 2019-02-19 13:11 UTC
While pinging an unreachable target, instead of returning "unreachable" to responses, the program just hanging there.

Tested with python 3.7.2 on MacOS (homebrew) and Python 3.6.7 on Ubuntu 18.04 with the same result.

Test code is quiet simple:

```
from pythonping import ping

ping('192.168.100.100', count=5, timeout=2, verbose=True)
```

**Comment by cveilleux** [comment] 2019-02-23 19:06
Confirming, same issue on ubuntu.

This is actually a duplicate of #11 . On unix platform, the timeout does not work because wrong function is used to count the time spent waiting.

**Closed** 2019-02-24 08:36 UTC
